server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grave
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.pojo.*
  configuration:
    map-underscore-to-camel-case: true